/**
 * Playwright-specific test file generator helper.
 *
 * Produces the source text of a `.spec.ts` file from a structured test plan
 * so that the `playwright-test-generator` agent has a deterministic template
 * to fill rather than free-forming TypeScript.
 *
 * Pure string generation — zero Playwright dependency at this layer.
 * Framework isolation: this file ONLY belongs in /frameworks/playwright/.
 */

import type { UnimplementedStub } from '../../common/types/index.js';
import { generateNotImplementedStub } from '../../common/agents-core/ac-scorer.js';
import { createLogger } from '../../common/utils/logger.js';

const log = createLogger('playwright-generator');

export interface PlaywrightTestSpec {
  /** Jira issue key, e.g. "SCRUM-42" */
  issueKey:    string;
  /** Human-readable story title */
  storyTitle:  string;
  /** Collection of ACs with their test body */
  acs: Array<{
    index:     number;    // 1-based
    acText:    string;
    testTitle: string;
    steps:     string[];  // plain-language step descriptions
    assertions: string[]; // plain-language assertion descriptions
    canImplement: boolean;
    reason?:   string;
    missing?:  string[];
  }>;
  /** Import path for page objects if any (relative from test file location) */
  pageObjectImports?: string[];
  /** Path to seed file if one is needed (e.g. Playwright/saucedemo/tests/seed.spec.ts) */
  seedFile?: string;
}

// ---------------------------------------------------------------------------
// Template builder
// ---------------------------------------------------------------------------

/**
 * Build the source text for a single `.spec.ts` file covering all implementable
 * ACs in the input spec. Returns the file content and any notimplemented stubs.
 */
export function buildPlaywrightSpecFile(spec: PlaywrightTestSpec): {
  specContent: string;
  stubs: Array<{ path: string; content: string }>;
} {
  const stubs: Array<{ path: string; content: string }> = [];
  const implementable = spec.acs.filter(ac => ac.canImplement);
  const notImplementable = spec.acs.filter(ac => !ac.canImplement);

  // Generate stubs for unimplementable ACs
  for (const ac of notImplementable) {
    const stub = generateNotImplementedStub({
      issueKey:  spec.issueKey,
      acText:    ac.acText,
      reason:    ac.reason ?? 'AC could not be determined',
      missing:   ac.missing ?? [],
      index:     ac.index - 1,
      framework: 'playwright',
    });
    stubs.push(stub);
    log.warn('AC cannot be automated', { issueKey: spec.issueKey, ac: ac.index, reason: ac.reason });
  }

  if (implementable.length === 0) {
    log.warn('No implementable ACs — returning empty spec', { issueKey: spec.issueKey });
    return { specContent: '', stubs };
  }

  // Build AC comment block at top of file
  const acComments = spec.acs
    .map(ac => ` * AC-${ac.index}: ${ac.acText}`)
    .join('\n');

  const seedComment = spec.seedFile
    ? `// seed: ${spec.seedFile}\n`
    : '';

  const importLines = [
    `import { test, expect } from '@playwright/test';`,
    ...(spec.pageObjectImports ?? []),
  ].join('\n');

  // Build individual test blocks
  const testBlocks = implementable.map(ac => {
    const stepComments = ac.steps.map(s => `      // ${s}`).join('\n');
    const assertComments = ac.assertions.map(a => `      // ASSERT: ${a}`).join('\n');
    return [
      `  // AC-${ac.index}: ${ac.acText}`,
      `  test('${escapeTestTitle(ac.testTitle)}', async ({ page }) => {`,
      stepComments,
      `      // TODO: implement steps above using page locators`,
      assertComments,
      `      // TODO: implement assertions above using expect()`,
      `  });`,
    ].join('\n');
  }).join('\n\n');

  const specContent = [
    `/**`,
    ` * Jira: ${spec.issueKey} — ${spec.storyTitle}`,
    ` *`,
    ` * Acceptance Criteria covered by this file:`,
    acComments,
    ` *`,
    ` * Generated by: playwright-test-generator agent`,
    ` * Framework:    Playwright`,
    ` */`,
    seedComment,
    importLines,
    ``,
    `test.describe('${spec.storyTitle}', () => {`,
    testBlocks,
    `});`,
    ``,
  ].join('\n');

  return { specContent, stubs };
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

function escapeTestTitle(title: string): string {
  return title.replace(/'/g, "\\'");
}

/**
 * Derive a safe filename from a test title and AC index.
 * E.g. "should redirect to /inventory" → "should-redirect-to-inventory"
 */
export function specFilename(params: {
  appPrefix: string;
  area:      string;
  seq:       number;
  title:     string;
}): string {
  const { appPrefix, area, seq, title } = params;
  const kebab = title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 60);
  return `${appPrefix}-tc-${area}-${String(seq).padStart(2, '0')}-${kebab}.spec.ts`;
}
