/**
 * Cypress-specific test file generator helper.
 *
 * Produces the source text of a `.cy.ts` file from a structured test plan.
 * Framework isolation: this file ONLY belongs in /frameworks/cypress/.
 *
 * Pure string generation — zero Cypress dependency at this layer.
 */

import { generateNotImplementedStub } from '../../common/agents-core/ac-scorer.js';
import { createLogger } from '../../common/utils/logger.js';

const log = createLogger('cypress-generator');

export interface CypressTestSpec {
  issueKey:    string;
  storyTitle:  string;
  baseUrl?:    string;
  acs: Array<{
    index:      number;
    acText:     string;
    testTitle:  string;
    steps:      string[];
    assertions: string[];
    canImplement: boolean;
    reason?:    string;
    missing?:   string[];
  }>;
  /** Optional beforeEach setup (e.g. cy.session login) */
  beforeEachSteps?: string[];
}

// ---------------------------------------------------------------------------
// Template builder
// ---------------------------------------------------------------------------

export function buildCypressSpecFile(spec: CypressTestSpec): {
  specContent: string;
  stubs: Array<{ path: string; content: string }>;
} {
  const stubs: Array<{ path: string; content: string }> = [];
  const implementable    = spec.acs.filter(ac => ac.canImplement);
  const notImplementable = spec.acs.filter(ac => !ac.canImplement);

  for (const ac of notImplementable) {
    const stub = generateNotImplementedStub({
      issueKey:  spec.issueKey,
      acText:    ac.acText,
      reason:    ac.reason ?? 'AC could not be determined',
      missing:   ac.missing ?? [],
      index:     ac.index - 1,
      framework: 'cypress',
    });
    stubs.push(stub);
    log.warn('AC cannot be automated', { issueKey: spec.issueKey, ac: ac.index, reason: ac.reason });
  }

  if (implementable.length === 0) {
    return { specContent: '', stubs };
  }

  const acComments = spec.acs
    .map(ac => ` * AC-${ac.index}: ${ac.acText}`)
    .join('\n');

  const beforeEachBlock = spec.beforeEachSteps && spec.beforeEachSteps.length > 0
    ? [
        `  beforeEach(() => {`,
        spec.beforeEachSteps.map(s => `    ${s}`).join('\n'),
        `  });`,
        ``,
      ].join('\n')
    : '';

  const itBlocks = implementable.map(ac => {
    const steps      = ac.steps.map(s => `    // ${s}`).join('\n');
    const assertions = ac.assertions.map(a => `    // ASSERT: ${a}`).join('\n');
    return [
      `  // AC-${ac.index}: ${ac.acText}`,
      `  it('${escapeTitle(ac.testTitle)}', () => {`,
      steps,
      `    // TODO: implement steps above using cy.get() / cy.contains()`,
      assertions,
      `    // TODO: implement assertions above using .should()`,
      `  });`,
    ].join('\n');
  }).join('\n\n');

  const specContent = [
    `/**`,
    ` * Jira: ${spec.issueKey} — ${spec.storyTitle}`,
    ` *`,
    ` * Acceptance Criteria covered:`,
    acComments,
    ` *`,
    ` * Generated by: cypress-test-generator agent`,
    ` * Framework:    Cypress`,
    ` */`,
    ``,
    `describe('${spec.storyTitle}', () => {`,
    beforeEachBlock,
    itBlocks,
    `});`,
    ``,
  ].join('\n');

  return { specContent, stubs };
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

function escapeTitle(t: string): string {
  return t.replace(/'/g, "\\'");
}

/**
 * Derive a safe filename.
 * E.g. appPrefix=saucedemo, area=auth, seq=1, title=valid login → saucedemo-cy-auth-01-valid-login.cy.ts
 */
export function cyFilename(params: {
  appPrefix: string;
  area:      string;
  seq:       number;
  title:     string;
}): string {
  const { appPrefix, area, seq, title } = params;
  const kebab = title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 60);
  return `${appPrefix}-cy-${area}-${String(seq).padStart(2, '0')}-${kebab}.cy.ts`;
}
