name: Playwright Tests
on:
  push:
    branches: [ main, master, dev, auto/** ]
  pull_request:
    branches: [ main, master, dev ]
jobs:
  test-saucedemo:
    name: SauceDemo E2E Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run SauceDemo Playwright tests
      run: npx playwright test --config=saucedemo/saucedemo.playwright.config.ts
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: saucedemo-playwright-report
        path: saucedemo/playwright-report/
        retention-days: 30

  test-orangehrm:
    name: OrangeHRM E2E Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      ORANGEHRM_USERNAME: ${{ secrets.ORANGEHRM_USERNAME }}
      ORANGEHRM_PASSWORD: ${{ secrets.ORANGEHRM_PASSWORD }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run OrangeHRM Playwright tests
      run: npx playwright test --config=OrangeHRM/orangehrm.playwright.config.ts
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: orangehrm-playwright-report
        path: OrangeHRM/playwright-report/
        retention-days: 30
